apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: addarr-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: '{{ .Values.storageClassName }}'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
